meta:

units:
  capx: 17.5
  capy: 17.95
  kx: 13.8
  ky: 13.8
  pinky_splay: 5
  pinky_adj: -3
  ring_splay: 8
  ring_adj: -10
  middle_splay: 8
  middle_adj: -10
  index_splay: 3
  index_adj: -4
  thumbsplay: 20
  thumb_offset: -14
  angle: 30
  $default_height: 0
  $default_width: 0
  xiao_x: 17.5
  xiao_y: 32.5
  sf: 16
  kp: 2.5
  pcbp: 4

points:
  key:
    footprints:
      mx_hotswap:
        type: choc
        params:
          hotswap: true
          keycaps: true
          reverse: true
        nets:
          from: =colrow
          to: =column_net
      diode:
        type: diode
        nets:
          from: =colrow
          to: =row_net
        anchor:
          shift: [0, -5]
  zones.matrix:
    anchor.shift: [100, -100]
    key:
      width: capx
      height: capy
      spread: capx + kp
      padding: capy + kp
      autobind: 0
    rows:
      bottom:
      home:
      top:
    columns:
      outer:
      pinky:
      ring:
      middle:
      index:
      inner:
    columns.outer:
      rows:
        bottom.skip: true
        home:
          row_net: P3
          column_net: P21
          bind: [0.5ky, 0.5kx, 0, 0]
        top:
          bind: [0, 0.5kx, 0.5ky, 0]
          row_net: P2
          column_net: P21
    columns.pinky:
      key:
        stagger: 2/3ky
        splay: -pinky_splay
        origin: [0, pinky_adj]
        column_net:
      rows:
        bottom:
          row_net: P4
          column_net: P20
        home:
          row_net: P3
          column_net: P20
        top:
          row_net: P2
          column_net: P20
    columns.ring:
      key:
        stagger: 3/5ky
        splay: -ring_splay
        origin: [0, ring_adj]
      rows:
        bottom:
          row_net: P4
          column_net: P19
        home:
          row_net: P3
          column_net: P19
        top:
          row_net: P2
          column_net: P19

    columns.middle:
      key:
        stagger: 1/2ky
        splay: -middle_splay
        origin: [0, middle_adj]
      rows:
        bottom:
          row_net: P4
          column_net: P18
        home:
          row_net: P3
          column_net: P18
        top:
          row_net: P2
          column_net: P18

    columns.index:
      key:
        stagger: -(4/5ky)
        splay: -index_splay
        origin: [0, index_adj]
      rows:
        bottom:
          row_net: P4
          column_net: P15
        home:
          row_net: P3
          column_net: P15
        top:
          row_net: P2
          column_net: P15

    columns.inner:
      key:
        stagger: -(2/3ky)
      rows:
        bottom.skip: true
        home:
          row_net: P3
          column_net: P14
        top:
          row_net: P2
          column_net: P14

  zones.thumbcluster:
    anchor:
      ref: matrix_index_bottom
      shift: [-.5kx, -22]
    key.$extends: points.zones.matrix.key
    columns:
      near:
      home:
      far:
      farthest:
    rows:
      thumb:
    columns.near:
      key:
      rows:
        thumb:
          row_net: P5
          column_net: P19
    columns.home:
      key:
        splay: -thumbsplay
        origin: [-10, thumb_offset]
      rows:
        thumb:
          row_net: P5
          column_net: P18

    columns.far:
      key:
        splay: -thumbsplay
        origin: [-10, thumb_offset]
      rows:
        thumb:
          row_net: P5
          column_net: P15

    columns.farthest:
      key:
        splay: -thumbsplay
        origin: [-10, thumb_offset]
      rows:
        thumb:
          row_net: P5
          column_net: P14
  zones.mcu:
    anchor:
      ref: matrix_inner_home
      shift: [capx+kp, (26.5 + -0.5xiao_y)]
    key:
      width: xiao_x
      height: xiao_y
  zones./mounting_hole_*/:
    key:
      width: 1
      height: 1
  zones.mounting_hole_1:
    anchor:
      ref: matrix_outer_home
      shift: [5,-11]
  zones.mounting_hole_2:
    anchor:
      ref: matrix_outer_top
      shift: [5,11]
  zones.mounting_hole_3:
    anchor:
      ref: matrix_middle_bottom
      shift: [-9,-31]
  zones.mounting_hole_4:
    anchor:
      ref: matrix_middle_top
      shift: [-kx,0]
  zones.mounting_hole_5:
    anchor:
      ref: matrix_middle_home
      shift: [-0.8kx,-ky]
  zones.mounting_hole_6:
    anchor:
      ref: matrix_inner_top
      shift: [-5,11]
  zones.mounting_hole_7:
    anchor:
      ref: matrix_inner_home
      shift: [0,-12]
  zones.mounting_hole_8:
    anchor:
      ref: thumbcluster_home_thumb
      shift: [-0.9kx,0]
  zones.mounting_hole_9:
    anchor:
      ref: thumbcluster_far_thumb
      shift: [-0.9kx,0]
  zones.mounting_hole_10:
    anchor:
      ref: thumbcluster_farthest_thumb
      shift: [-0.9kx,0]
  zones.mounting_hole_11:
    anchor:
      ref: thumbcluster_farthest_thumb
      shift: [0.75kx,0]
outlines:
  raw:
    - what: rectangle
      where:
        - /thumbcluster_*/
        - /matrix_*/
      asym: source
      size: [kx + px, ky + py]
      corner: px
  trrs:
    - what: rectangle
      where:
        ref: matrix_inner_home
        shift:  [1,-20]
      size: [12, 6]
  keycaps:
    - what: rectangle
      where:
        - /thumbcluster_*/
        - /matrix_*/
      size: [capx, capy]
  key_punchout:
    - what: rectangle
      where:
        - /thumbcluster_*/
        - /matrix_*/
      asym: source
      size: [kx, ky]
  mcu_punchout:
    - what: rectangle
      fillet: 3
      where:
        - /mcu/
      size: [xiao_x+1, xiao_y+1]
  plate:
    - what: polygon
      fillet: 3
      points:
        - ref: matrix_middle_top
          shift: [0.5kx+px, 0.5kx+py]
        - ref: matrix_middle_top
          shift: [-0.5kx-px, 0.5kx+py]
        - ref: matrix_ring_top
          shift: [-0.5kx-px, 0.5kx+py]
        - ref: matrix_pinky_top
          shift: [-0.5kx-px, 0.5kx+py]
        - ref: matrix_outer_top
          shift: [-0.5kx-px, 0.5ky+py]
        - ref: matrix_outer_home
          shift: [-0.5kx-px, -0.5ky-py-2]
        - ref: matrix_pinky_bottom
          shift: [-0.5kx-px, -0.5ky-py]
        - ref: matrix_pinky_bottom
          shift: [0.5kx+px, -0.5ky-py]
        - ref: thumbcluster_near_thumb
          shift: [-0.5kx-px, -0.5ky-py]
        - ref: thumbcluster_home_thumb
          shift: [-0.5kx-px, -0.5ky-py]
        - ref: thumbcluster_far_thumb
          shift: [-0.5kx-px, -0.5ky-py]
        - ref: thumbcluster_farthest_thumb
          shift: [-0.5kx-px, -0.5ky-py]
        - ref: thumbcluster_farthest_thumb
          shift: [0.5kx+px+5, -0.5ky-py]
        - ref: thumbcluster_farthest_thumb
          shift: [0.5kx+px+5, 0.5ky+py]
        - ref: thumbcluster_farthest_thumb
          shift: [-0.5kx-px, 0.5ky+py]
        - ref: thumbcluster_far_thumb
          shift: [0.5kx+px, 0.5ky+py]
        - ref: thumbcluster_far_thumb
          shift: [-0.5kx-px, 0.5ky+py]
        - ref: thumbcluster_home_thumb
          shift: [0.5kx+px, 0.5ky+py]
        - ref: mcu
          shift: [-0.5xiao_x-px, -0.5xiao_y-2.5]
        - ref: mcu
          shift: [0.5xiao_x+px, -0.5xiao_y-2.5]
        - ref: mcu
          shift: [0.5xiao_x+px, 0.5xiao_y+py]
        - ref: mcu
          shift: [-0.5xiao_x-px, 0.5xiao_y+py]
        - ref: matrix_index_top
          shift: [0.5kx+px, 0.5ky+py]
  screw_holes:
    - what: circle
      where:
        - /mounting_hole_*/
      radius: 1
  baseplate:
    - plate
    - -screw_holes
  preview:
    - plate
    - -mcu_punchout
    - -key_punchout
    - -screw_holes
    - -trrs
pcbs:
  swallowtail:
    outlines:
      main:
        outline: baseplate
    footprints:
      - what: mx
        where:
          - /matrix_.*/
          - /thumbcluster_.*/
        params:
          hotswap: true
          keycaps: true
          from: "{{colrow}}"
          to: "{{column_net}}"
      - what: diode
        where:
          - /matrix_.*/
          - /thumbcluster_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      - what: promicro
        where:
          ref:
            - mcu
          rotate: ring_splay + middle_splay + index_splay
      - what: mountinghole
        where:
          - /mounting_hole_*/
